// Generated via `forge inspect FactionWar abi` in ../../contracts. Regenerate
// after any change to contracts/src/FactionWar.sol and keep this in sync —
// do not hand-edit.
export const FACTION_WAR_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_jackpot", type: "address", internalType: "address" },
      { name: "_usdc", type: "address", internalType: "address" },
      { name: "_redReferrer", type: "address", internalType: "address" },
      { name: "_blueReferrer", type: "address", internalType: "address" },
      { name: "_greenReferrer", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "FACTION_COUNT",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "attack",
    inputs: [
      { name: "normals", type: "uint8[]", internalType: "uint8[]" },
      { name: "bonusball", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "drawingResolved",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "factionReferrer",
    inputs: [{ name: "", type: "uint8", internalType: "enum FactionWar.Faction" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFactionScores",
    inputs: [],
    outputs: [
      { name: "territory", type: "uint256[]", internalType: "uint256[]" },
      { name: "herald", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMapState",
    inputs: [],
    outputs: [
      { name: "ballMax", type: "uint8", internalType: "uint8" },
      { name: "controllers", type: "uint8[]", internalType: "enum FactionWar.Faction[]" },
      { name: "liveCounts", type: "uint256[][]", internalType: "uint256[][]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getZone",
    inputs: [{ name: "number", type: "uint8", internalType: "uint8" }],
    outputs: [
      { name: "controller", type: "uint8", internalType: "enum FactionWar.Faction" },
      { name: "lastCapturedDrawing", type: "uint256", internalType: "uint256" },
      { name: "liveCounts", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "heraldBonus",
    inputs: [{ name: "", type: "uint8", internalType: "enum FactionWar.Faction" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "heraldByDrawing",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum FactionWar.Faction" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "jackpot",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IJackpot" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "joinFaction",
    inputs: [{ name: "f", type: "uint8", internalType: "enum FactionWar.Faction" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lastResolvedDrawing",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "playerFaction",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum FactionWar.Faction" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolveDrawing",
    inputs: [{ name: "drawingId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "territoryCount",
    inputs: [{ name: "", type: "uint8", internalType: "enum FactionWar.Faction" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "triggerBattle",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "BattleTriggered",
    inputs: [
      { name: "drawingId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "faction", type: "uint8", indexed: true, internalType: "enum FactionWar.Faction" },
      { name: "caller", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FactionJoined",
    inputs: [
      { name: "player", type: "address", indexed: true, internalType: "address" },
      { name: "faction", type: "uint8", indexed: false, internalType: "enum FactionWar.Faction" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ZoneAttacked",
    inputs: [
      { name: "drawingId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "faction", type: "uint8", indexed: true, internalType: "enum FactionWar.Faction" },
      { name: "normals", type: "uint8[]", indexed: false, internalType: "uint8[]" },
      { name: "bonusball", type: "uint8", indexed: false, internalType: "uint8" },
      { name: "player", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ZonesResolved",
    inputs: [
      { name: "drawingId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "capturedZones", type: "uint8[]", indexed: false, internalType: "uint8[]" },
      { name: "winningFactions", type: "uint8[]", indexed: false, internalType: "enum FactionWar.Faction[]" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyResolved", inputs: [] },
  { type: "error", name: "DrawingNotReady", inputs: [] },
  { type: "error", name: "DrawingNotSettled", inputs: [] },
  { type: "error", name: "InvalidFaction", inputs: [] },
  { type: "error", name: "NoFaction", inputs: [] },
  { type: "error", name: "RefundFailed", inputs: [] },
  { type: "error", name: "UsdcApproveFailed", inputs: [] },
  { type: "error", name: "UsdcTransferFailed", inputs: [] },
] as const;
